version: "3"

services:
  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zero-manga
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:5432